version: "3.8"

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
      args:
        - VITE_EDGE_CONFIG=${VITE_EDGE_CONFIG}
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
