name: Build and Test

on:
  pull_request:

env:
  IMAGE_NAME: yz13-portfolio
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (without pushing)
        run: |
          docker build \
            --build-arg VITE_EDGE_CONFIG="${{ secrets.EDGE_CONFIG }}" \
            --build-arg VITE_SUPABASE_URL="${{ secrets.SUPABASE_URL }}" \
            -t $IMAGE_NAME:$IMAGE_TAG .
